#version 430 core

layout(local_size_x = 20, local_size_y = 20, local_size_z = 1) in;

struct Chunk {
    float x;
    float y;
    float Cw;
    int id;

    uint cached_start;
    uint cached_count;

    uint test_points_start;
    uint test_points_count;
};

layout (std430, binding = 0) buffer DataBuffer {
    Chunk chunks[];
};

struct CachedEntry {
    int key;
    uint start;
    uint count;
};

layout (std430, binding = 1) buffer CachedEntries {
    CachedEntry cached_chunks[];
};

layout (std430, binding = 2) buffer CachedIndices {
    int chunk_indices[];
};

struct TestPoint{
    float x;
    float y;
    float range;
    uint moving;
    uint trash;
    int chunk_id;
};

layout (std430, binding = 3) buffer TestPoints {
    TestPoint test_points[];
};

layout (std430, binding = 4) buffer MaxRange {
    uint max_chunk_search_range;
};

layout (std430, binding = 5) buffer MovementVars {
    uint movement_amount;
};

layout (std430, binding = 6) buffer MovmentVarsSecond {
    uint movement_step;
};

struct MovedPoints{
    float x;
    float y;
    float range;
    uint moving;
    int chunk_id;
};

layout (std430, binding = 7) buffer MovedPoints {
    MovedPoints moved_points[20000];
};

layout(std430, binding = 8) buffer MovedCounter {
    uint moved_count;
};

uniform uint grid_length;

TestPoint find_closest_point(TestPoint p, float smallest_distance, Chunk c, uint test_point_index){
    bool found_smallest = false;
    TestPoint ps = p;

    for (uint range_index = 0; range_index < max_chunk_search_range; range_index++){
        CachedEntry e = cached_chunks[c.cached_start + range_index];
        for (uint chunk_entry_id = 0; chunk_entry_id < e.count; chunk_entry_id++){
            Chunk ct = chunks[chunk_indices[e.start + chunk_entry_id]];
            for (uint test_point_testing_index = 0; test_point_testing_index < ct.test_points_count; test_point_testing_index++){
                TestPoint tt = test_points[ct.test_points_start + test_point_testing_index];

                vec2 test_point_a = vec2(tt.x, tt.y);
                vec2 test_point_b = vec2(p.x, p.y);

                float dist = distance(test_point_a, test_point_b);

                if (dist <= p.range && dist < smallest_distance){
                    ps = tt;
                    smallest_distance = dist;
                    found_smallest = true;
                }
            }
        }
    }
    return ps;
}

uint cube_collisions(vec2 box_point_1, vec2 box_point_2, vec2 point){
    if (point.x < box_point_1.x){
        return 0;
    } else if (point.y > box_point_1.y){
        return 0;
    } else if (point.x > box_point_2.x){
        return 0;
    } else if (point.y < box_point_2.y){
        return 0;
    } else {
        return 1;
    }
}

vec2 move_towards(TestPoint target, TestPoint p, float move_amount, float step) {
    vec2 pos = vec2(p.x, p.y);
    vec2 target_pos = vec2(target.x, target.y);

    vec2 dir = target_pos - pos;
    float dist = length(dir);

    if (dist <= 0.0001) {
        return pos;
    }

    float speed = move_amount * step;

    if (speed >= dist) {
        return target_pos;
    }

    return pos + (dir / dist) * speed;
}

vec2 snap_to_grid(vec2 pos, uint grid_size){
    return floor(pos / grid_size);
}

void main() {
    uint chunkIndex = (gl_GlobalInvocationID.y * 20) + gl_GlobalInvocationID.x;

    if (chunkIndex >= 400) return;

    Chunk c = chunks[chunkIndex];

    for (int test_point_index = int(c.test_points_count) - 1; test_point_index >= 0 ; --test_point_index){
        TestPoint p = test_points[c.test_points_start + test_point_index];
        float smallest_distance = 1000;

        if (p.trash == 1){
            continue;
        }

        if (p.moving == 1) {
            TestPoint ps = find_closest_point(p, smallest_distance, c, test_point_index);

            vec2 new_pos = move_towards(ps, p, movement_amount, movement_step);

            uint idx = c.test_points_start + test_point_index;

            test_points[idx].x = new_pos.x;
            test_points[idx].y = new_pos.y;

            vec2 test_point_pos = vec2(ps.x, ps.y);
            vec2 chunk_pos_top_left = vec2(chunks[ps.chunk_id].x, chunks[ps.chunk_id].y);
            vec2 chunk_pos_bottom_right = vec2(chunks[ps.chunk_id].x + chunks[ps.chunk_id].Cw, chunks[ps.chunk_id].y + chunks[ps.chunk_id].Cw);

            uint colliding = cube_collisions(chunk_pos_top_left, chunk_pos_bottom_right, test_point_pos);

            if (!colliding){
                vec2 grid_point = snap_to_grid(test_point_pos, 32);
                int grid_points_chunk_index = int((grid_point.y * 20) + grid_point.x);

                uint index = atomicAdd(moved_count, 1);

                if (index < 20000){
                    moved_points[index].x = new_pos.x;
                    moved_points[index].y = new_pos.y;
                    moved_points[index].range = ps.range;
                    moved_points[index].chunk_id = ps.chunk_id;
                    moved_points[index].moving = ps.moving;

                    test_points[idx].trash = 1;
                }
            }
        }
    }
}